// Development preview content used only when DATABASE_URL is not configured.
// Production and deployed environments continue to read from Prisma.

export const previewPosts = [
  {
    slug: "designing-calm-digital-products",
    title: "Designing Calm Digital Products in a Noisy World",
    excerpt: "A practical framework for turning complex product decisions into clear, humane experiences that respect attention.",
    category: "software-engineering",
    author: {
      name: "Ayesha Khan",
      bio: "Writes on software architecture and computer science education from the classroom and the codebase.",
    },
    date: "2026-08-14T08:00:00.000Z",
    image: "https://images.unsplash.com/photo-1558655146-d09347e92766?w=1400&auto=format&fit=crop&q=80",
    featured: true,
    popular: true,
    tags: ["product design", "systems", "focus"],
    readingTime: 7,
    references: [],
    content: [
      { type: "p", text: "Good digital products rarely win because they contain the most features. They win because they make the next useful action obvious, dependable, and easy to complete." },
      { type: "heading", text: "Start with the user's attention" },
      { type: "p", text: "A calm interface does not mean a quiet or empty interface. It means the hierarchy is intentional: primary actions are clear, supporting detail is available when needed, and visual noise never competes with the task in front of the user." },
      { type: "quote", text: "Clarity is not a visual style. It is a product decision." },
      { type: "heading", text: "Build rhythm into the experience" },
      { type: "p", text: "Consistent spacing, readable line lengths, and predictable controls create a sense of rhythm. That rhythm lets people learn the interface quickly and spend their energy on the work rather than on decoding the screen." },
    ],
  },
  {
    slug: "shipping-ai-features-without-the-hype",
    title: "Shipping AI Features Without the Hype",
    excerpt: "What product teams should measure before adding a model, a copilot, or another clever demo to the roadmap.",
    category: "artificial-intelligence",
    author: {
      name: "Hassan Raza",
      bio: "Covers applied AI and infrastructure, with a focus on what actually ships to production.",
    },
    date: "2026-08-11T08:00:00.000Z",
    image: "https://images.unsplash.com/photo-1677442136019-21780ecad995?w=1400&auto=format&fit=crop&q=80",
    featured: true,
    popular: true,
    tags: ["AI", "product", "delivery"],
    readingTime: 6,
    references: [],
    content: [
      { type: "p", text: "The hard part of an AI feature is rarely the first prompt. The hard part is designing the feedback loops, failure states, and operational boundaries that make the feature useful after launch." },
      { type: "heading", text: "Define the decision before the model" },
      { type: "p", text: "Start by naming the human decision the system should support. When the intended decision is fuzzy, a model can produce impressive output without creating measurable value." },
      { type: "heading", text: "Treat evaluation as product design" },
      { type: "p", text: "A useful evaluation set is a living expression of product quality. It should include common cases, edge cases, and the moments where a confident wrong answer would create real harm." },
    ],
  },
  {
    slug: "web-performance-is-a-team-sport",
    title: "Web Performance Is a Team Sport",
    excerpt: "The fastest sites are not created by one heroic optimization; they emerge from shared budgets, habits, and ownership.",
    category: "web-development",
    author: {
      name: "Usman Tariq",
      bio: "Writes about the App Router, TypeScript, and the parts of API design nobody warns you about.",
    },
    date: "2026-08-07T08:00:00.000Z",
    image: "https://images.unsplash.com/photo-1461749280684-dccba630e2f6?w=1400&auto=format&fit=crop&q=80",
    featured: false,
    popular: true,
    tags: ["performance", "frontend", "web"],
    readingTime: 5,
    references: [],
    content: [
      { type: "p", text: "Performance is an experience property with technical causes. A slow page might be a rendering problem, an image problem, a content problem, or a decision problem that started long before code was written." },
      { type: "heading", text: "Make the budget visible" },
      { type: "p", text: "Teams improve what they can see. Define a small number of budgets for JavaScript, image weight, interaction latency, and meaningful paint, then review them alongside feature work." },
      { type: "heading", text: "Optimize the path people actually take" },
      { type: "p", text: "A performance report is most useful when it is connected to a real journey. Follow the first visit, the return visit, and the critical conversion path instead of treating every page as equally important." },
    ],
  },
  {
    slug: "zero-trust-for-small-teams",
    title: "Zero Trust for Small Teams",
    excerpt: "A grounded security playbook for teams that need stronger access controls without adding unnecessary ceremony.",
    category: "cybersecurity",
    author: {
      name: "Bilal Ahmed",
      bio: "Security engineer covering identity, authentication, and pragmatic zero-trust for small teams.",
    },
    date: "2026-08-03T08:00:00.000Z",
    image: "https://images.unsplash.com/photo-1563013544-824ae1b704d3?w=1400&auto=format&fit=crop&q=80",
    featured: false,
    popular: false,
    tags: ["security", "identity", "teams"],
    readingTime: 8,
    references: [],
    content: [
      { type: "p", text: "Zero trust is often described as a sweeping transformation. For a small team, it is more useful as a set of concrete questions about identity, device health, least privilege, and evidence." },
      { type: "heading", text: "Begin with access inventory" },
      { type: "p", text: "List the systems that matter, who can reach them, and what happens when a person changes teams. The first improvement is often removing access that no longer has a clear owner." },
      { type: "heading", text: "Prefer repeatable controls" },
      { type: "p", text: "A simple, enforced process for onboarding, offboarding, and reviewing privileged access is more valuable than a complicated policy nobody follows." },
    ],
  },
  {
    slug: "the-editorial-system-behind-consistent-content",
    title: "The Editorial System Behind Consistent Content",
    excerpt: "How lightweight planning and review rituals help a growing publication stay useful, specific, and trustworthy.",
    category: "digital-marketing",
    author: {
      name: "Sara Malik",
      bio: "Writes on startups, marketing strategy, and the productivity habits that survive contact with a real week.",
    },
    date: "2026-07-30T08:00:00.000Z",
    image: "https://images.unsplash.com/photo-1455390582262-044cdead277a?w=1400&auto=format&fit=crop&q=80",
    featured: false,
    popular: false,
    tags: ["editorial", "content", "strategy"],
    readingTime: 5,
    references: [],
    content: [
      { type: "p", text: "Consistent publishing is not the result of writing faster. It is the result of reducing ambiguity: who the article is for, what it should help them do, and what standard it must meet before it goes live." },
      { type: "heading", text: "Make the brief do more work" },
      { type: "p", text: "A strong brief clarifies the reader, the promise, the evidence, and the desired next step. It gives a writer room to think while protecting the article from drift." },
      { type: "heading", text: "Review for usefulness, not just polish" },
      { type: "p", text: "Line edits matter, but the most valuable review question is simpler: will this change what the reader understands or does?" },
    ],
  },
  {
    slug: "learning-in-public-without-losing-the-thread",
    title: "Learning in Public Without Losing the Thread",
    excerpt: "A practical note-taking system for turning scattered research into durable ideas and better technical decisions.",
    category: "productivity",
    author: {
      name: "Zainab Sheikh",
      bio: "Writes on data science, applied machine learning, and turning experiments into production models.",
    },
    date: "2026-07-26T08:00:00.000Z",
    image: "https://images.unsplash.com/photo-1456324504439-367cee3b3c32?w=1400&auto=format&fit=crop&q=80",
    featured: false,
    popular: false,
    tags: ["learning", "notes", "research"],
    readingTime: 4,
    references: [],
    content: [
      { type: "p", text: "Public learning works best when it is treated as a trail of decisions rather than a stream of finished answers. The goal is not to perform certainty; it is to make progress legible." },
      { type: "heading", text: "Capture the question first" },
      { type: "p", text: "A note anchored to a question is easier to revisit than a note that only records a topic. The question gives later readers a reason to care and a way to test the idea." },
      { type: "heading", text: "Close the loop" },
      { type: "p", text: "Return to old notes with what changed, what held up, and what you would do differently. That small habit turns information into judgment." },
    ],
  },
];

export function getPreviewPost(slug) {
  return previewPosts.find((post) => post.slug === slug) || null;
}
